#!/bin/bash

function checkinternetconnection {

    wget -q --tries=10 --timeout=5 http://www.google.com -O /tmp/index.google &> /dev/null

    if [ -s /tmp/index.google ];then
	echo
	return 0
    else
        echo
	return 1
    fi
}
