#!/bin/bash

clear 

echo " 

  REMOVE Online Search in Dash
  ----------------------------
  
  If you choose to do this, the following package will be removed:

      unity-lens-music unity-lens-photos unity-lens-video

"

if prompt "  Would you like to remove Online Search in Dash?"; then
    echo $pwd | sudo apt-get purge -y unity-lens-music unity-lens-photos unity-lens-video

    gsettings set com.canonical.Unity.Lenses disabled-scopes "['more_suggestions-amazon.scope', 'more_suggestions-u1ms.scope', 'more_suggestions-populartracks.scope', 'music-musicstore.scope', 'more_suggestions-ebay.scope', 'more_suggestions-ubuntushop.scope', 'more_suggestions-skimlinks.scope']"
fi
