#!/bin/bash 

clear 

echo " 

  INSTALL Shutter
  ------------------

  Shutter is a rich screenshot and editing program. It is comparable
  to the snipping tool available in Microsoft Windows.

  Find out more: shutter-project.org

  If you choose to do this, the following package will be installed:

      shutter

  
  Note: additional packages listed as dependencies will also be installed.

"

if prompt "  Would you like to install Shutter?"; then
    echo $pwd | sudo apt-get install -y shutter
fi
