#!/bin/bash

clear 

echo " 

  INSTALL GIMP
  ------------

  GIMP (GNU Image manipulation) is a free image retouching and editing tool.
  It performs similar functions to Adobe Photoshop.

  Find out more: gimp.org

  If you choose to do this, the following package will be installed:

      gimp

  
  Note: additional packages listed as dependencies will also be installed.

"

if prompt "  Would you like to install Gimp?"; then
    echo $pwd | sudo apt-get install -y gimp
fi
