#!/bin/bash

clear 

echo " 

  REMOVE xTerm
  ------------
  
  If you choose to do this, the following package will be removed:

      xterm
"

if prompt "  Would you like to remove xTerm?"; then
    echo $pwd | sudo apt-get purge -y xterm
fi
