#!/bin/bash

clear 

echo " 

  REMOVE Totem
  ------------
  
  If you choose to do this, the following package will be removed:

      totem
"

if prompt "  Would you like to remove Totem?"; then
    echo $pwd | sudo apt-get purge -y totem
fi
