#!/bin/bash

clear 

echo " 

  REMOVE Mozilla Thunderbird
  --------------------------
  
  If you choose to do this, the following package will be removed:

      thunderbird
"

if prompt "  Would you like to remove Mozilla Thunderbird?"; then
    echo $pwd | sudo apt-get purge -y thunderbird
fi
