#!/bin/bash

clear 

echo " 

  REMOVE Transmission
  -------------------
  
  If you choose to do this, the following package will be removed:

      transmission-gtk
"

if prompt "  Would you like to remove Transmission?"; then
    echo $pwd | sudo apt-get purge -y transmission-gtk
fi
